### ISSUE TITLE
BUGFIX: Username not getting passed on registration.

### ISSUE THREAD

**Issue by mattkbrat** [Nauxiliary/Group2#36]
Username not getting passed on registration. Usernames should be emails and should not be separate.

Environment:

Request Method: POST
Request URL: http://127.0.0.1:8000/accounts/register/

Django Version: 4.0.2
Python Version: 3.9.1
Installed Applications:
['common.apps.CommonConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'accounts.apps.AccountsConfig',
 'crispy_forms']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (UNIQUE constraint failed: accounts_user.username) was the direct cause of the following exception:
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Matthew\Documents\GitHub\Group2\aap\accounts\views.py", line 20, in register_view
    user = form.save()
  File "C:\Users\Matthew\Documents\GitHub\Group2\aap\accounts\forms.py", line 22, in save
    user.save()
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\contrib\auth\base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\db\models\base.py", line 743, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\db\models\base.py", line 780, in save_base
    updated = self._save_table(
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\db\models\base.py", line 885, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\db\models\base.py", line 923, in _do_insert
    return manager._insert(
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\db\models\query.py", line 1301, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1441, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Matthew\Documents\GitHub\Group2\AAP\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 416, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: IntegrityError at /accounts/register/
Exception Value: UNIQUE constraint failed: accounts_user.username

**Comment by mattkbrat** [comment]
Django was generating a username when reading the models. Cleared out the migrations and database and it works as intended now. TODO: Add error message when email is not unique.
